### Simple MLP Regression

The y variable is a vector

In [42]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
# load data
import pandas as pd
df = pd.read_csv("county-year-agg.csv")

# dealing with nas
df['VACO2'].isna().sum()

# replace with median (not sure which method to choose)
VACO2_median = df['VACO2'].median()
df['VACO2'].fillna(VACO2_median, inplace=True)

# min-max predictors
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

# list of T and P cols
t_cols = ['T' + str(i) for i in range(1, 13)]
p_cols = ['P' + str(i) for i in range(1, 13)]

cols_select = ['Income', 'DSCI', 'VACO2'] + t_cols + p_cols
scaler = MinMaxScaler()
#scaler = StandardScaler()

scaled_cols = scaler.fit_transform(df[cols_select])
scaled_df = pd.DataFrame(scaled_cols, columns=cols_select)

cols_add = ['County','Year','Agriculture', 'Aquaculture','Barren','Developed', 'Forest','Grassland','Open_Water','Shrubland','Wetlands']
scaled_df[cols_add] = df[cols_add]

# replacing County with numeric value
scaled_df['County'].replace(['Accomack', 'Fauquier', 'Greensville', 'Hanover', 'Rockingham', 'Wise'],
                        [1,2,3,4,5,6], inplace=True)

# one-hot code year
onehot = pd.get_dummies(scaled_df['Year'])
df_scaled = pd.concat([scaled_df, onehot], axis=1)

# drop the original year column
df_scaled.drop('Year', axis=1, inplace=True)

# scaled data
df_scaled.T

0         1         2         3         4         5   \
Income       0.122746  0.136296  0.149829  0.150694  0.175042  0.178694   
DSCI         0.455999  0.137497  0.250377  0.325839  0.376057  0.017214   
VACO2        1.000000  0.422880  0.740739  0.242746  0.032386  0.415422   
T1           0.683168  0.683168  0.663366  0.693069  0.891089  0.881188   
T2           0.761905  0.676190  0.628571  0.761905  0.914286  0.857143   
T3           0.712963  0.592593  0.592593  0.694444  0.916667  0.694444   
T4           0.769231  0.615385  0.634615  0.721154  0.923077  0.711538   
T5           0.777778  0.646465  0.666667  0.737374  0.959596  0.696970   
T6           0.800000  0.610000  0.700000  0.700000  0.930000  0.700000   
T7           0.803922  0.607843  0.754902  0.705882  0.950980  0.676471   
T8           0.808081  0.656566  0.767677  0.717172  0.979798  0.676768   
T9           0.814433  0.639175  0.804124  0.711340  0.969072  0.659794   
T10          0.717172  0.636364  0.787879  0.676768  0.959596  0.636364   
T11          0.734694  0.704082  0.795918  0.734694  0.938776  0.673469   
T12          0.744898  0.673469  0.724490  0.846939  0.938776  0.642857   
P1           0.127916  0.402809  0.692751  0.247805  0.280662  0.561826   
P2           0.156048  0.337116  0.809905  0.195512  0.360846  0.595048   
P3           0.167751  0.385153  0.837069  0.105809  0.323692  0.638226   
P4           0.135917  0.328424  0.771318  0.079845  0.332300  0.636693   
P5           0.236423  0.242031  0.794864  0.000000  0.384593  0.627804   
P6           0.181046  0.157948  0.663383  0.036345  0.212296  0.676630   
P7           0.201962  0.148850  0.546008  0.078146  0.203654  0.666441   
P8           0.194454  0.316811  0.600347  0.225650  0.220797  0.570191   
P9           0.288798  0.413642  0.521902  0.241865  0.259387  0.489675   
P10          0.150632  0.480078  0.514739  0.145449  0.437966  0.265954   
P11          0.280665  0.551785  0.280665  0.185931  0.360905  0.313538   
P12          0.330289  0.637301  0.150854  0.210371  0.470536  0.396877   
County       1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
Agriculture  0.328149  0.316069  0.321777  0.260725  0.270210  0.245500   
Aquaculture  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
Barren       0.012280  0.019432  0.098342  0.023123  0.026444  0.045041   
Developed    0.062278  0.062453  0.023141  0.069094  0.066762  0.065002   
Forest       0.032290  0.026081  0.302307  0.061102  0.051508  0.054102   
Grassland    0.005097  0.007146  0.004368  0.011748  0.003030  0.021884   
Open_Water   0.048362  0.050323  0.043351  0.048192  0.046773  0.048375   
Shrubland    0.009128  0.011391  0.000000  0.017834  0.019485  0.012470   
Wetlands     0.502416  0.507106  0.206714  0.508182  0.515788  0.507627   
2008         1.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2009         0.000000  1.000000  0.000000  0.000000  0.000000  0.000000   
2010         0.000000  0.000000  1.000000  0.000000  0.000000  0.000000   
2011         0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
2012         0.000000  0.000000  0.000000  0.000000  1.000000  0.000000   
2013         0.000000  0.000000  0.000000  0.000000  0.000000  1.000000   
2014         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2015         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2016         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2017         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2018         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2019         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2020         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2021         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2022         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

                   6         7         8   

In [57]:
# split into X and y dataframes

y_vars = ['Agriculture', 'Aquaculture','Barren','Developed', 'Forest','Grassland','Open_Water','Shrubland','Wetlands']
x_vars = df_scaled.columns[~df_scaled.columns.isin(y_vars)]

y = df_scaled[y_vars]
X = df_scaled[x_vars]

X.T

0         1         2         3         4         5         6   \
Income  0.122746  0.136296  0.149829  0.150694  0.175042  0.178694  0.194857   
DSCI    0.455999  0.137497  0.250377  0.325839  0.376057  0.017214  0.088084   
VACO2   1.000000  0.422880  0.740739  0.242746  0.032386  0.415422  0.504482   
T1      0.683168  0.683168  0.663366  0.693069  0.891089  0.881188  0.574257   
T2      0.761905  0.676190  0.628571  0.761905  0.914286  0.857143  0.590476   
T3      0.712963  0.592593  0.592593  0.694444  0.916667  0.694444  0.537037   
T4      0.769231  0.615385  0.634615  0.721154  0.923077  0.711538  0.548077   
T5      0.777778  0.646465  0.666667  0.737374  0.959596  0.696970  0.575758   
T6      0.800000  0.610000  0.700000  0.700000  0.930000  0.700000  0.570000   
T7      0.803922  0.607843  0.754902  0.705882  0.950980  0.676471  0.558824   
T8      0.808081  0.656566  0.767677  0.717172  0.979798  0.676768  0.575758   
T9      0.814433  0.639175  0.804124  0.711340  0.969072  0.659794  0.597938   
T10     0.717172  0.636364  0.787879  0.676768  0.959596  0.636364  0.585859   
T11     0.734694  0.704082  0.795918  0.734694  0.938776  0.673469  0.602041   
T12     0.744898  0.673469  0.724490  0.846939  0.938776  0.642857  0.602041   
P1      0.127916  0.402809  0.692751  0.247805  0.280662  0.561826  0.432405   
P2      0.156048  0.337116  0.809905  0.195512  0.360846  0.595048  0.396441   
P3      0.167751  0.385153  0.837069  0.105809  0.323692  0.638226  0.346831   
P4      0.135917  0.328424  0.771318  0.079845  0.332300  0.636693  0.327132   
P5      0.236423  0.242031  0.794864  0.000000  0.384593  0.627804  0.416175   
P6      0.181046  0.157948  0.663383  0.036345  0.212296  0.676630  0.219090   
P7      0.201962  0.148850  0.546008  0.078146  0.203654  0.666441  0.153248   
P8      0.194454  0.316811  0.600347  0.225650  0.220797  0.570191  0.219757   
P9      0.288798  0.413642  0.521902  0.241865  0.259387  0.489675  0.359825   
P10     0.150632  0.480078  0.514739  0.145449  0.437966  0.265954  0.248137   
P11     0.280665  0.551785  0.280665  0.185931  0.360905  0.313538  0.273241   
P12     0.330289  0.637301  0.150854  0.210371  0.470536  0.396877  0.241897   
County  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
2008    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2009    0.000000  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2010    0.000000  0.000000  1.000000  0.000000  0.000000  0.000000  0.000000   
2011    0.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000   
2012    0.000000  0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
2013    0.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000   
2014    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000   
2015    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2016    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2017    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2018    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2019    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2020    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2021    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2022    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

              7         8         9   ...        80        81        82  \
Income  0.215225  0.256775  0.319022  ...  0.074534  0.086890  0.092843   
DSCI    0.059170  0.030167  0.036702  ...  0.000000  0.105808  0.087636   
VACO2   0.513963  0.643925  0.405723  ...  0.415422  0.504482  0.513963   
T1      0.594059  0.722772  0.841584  ...  0.336634  0.000000  0.099010   
T2      0.542857  0.838095  0.885714  ...  0.333333  0.038095  0.057143   
T3      0.490741  0.842593  0.787037  ...  

In [77]:
from sklearn.model_selection import train_test_split
# leave out some counties- take 80pct of counties for train and rest for test?

# Try again without hard coding the numbers - take an 80% fraction or so
# did not shuffle so that the years would stay in order... but not sure that worked...
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, shuffle=False, random_state=42)

# save input parameters to np.array
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# (interpolation function (BEFORE SCALING)) ?? Not sure anymore what inperpolating meanss

## How to deal with the years when one hot encoded like this?

print(X_train)
print('----')
print(y_train)

[[0.12274599 0.45599859 1.         ... 0.         0.         0.        ]
 [0.13629599 0.13749679 0.42288031 ... 0.         0.         0.        ]
 [0.14982868 0.25037664 0.74073902 ... 0.         0.         0.        ]
 ...
 [0.21716333 0.25521051 0.405723   ... 0.         0.         0.        ]
 [0.24362302 0.1181613  0.64346133 ... 0.         0.         0.        ]
 [0.2673658  0.04470402 0.47003265 ... 0.         0.         0.        ]]
----
[[3.28149486e-01 0.00000000e+00 1.22796590e-02 6.22778866e-02
  3.22901614e-02 5.09701475e-03 4.83618740e-02 9.12813267e-03
  5.02415785e-01]
 [3.16069322e-01 0.00000000e+00 1.94318020e-02 6.24526509e-02
  2.60810856e-02 7.14554809e-03 5.03230253e-02 1.13909995e-02
  5.07105567e-01]
 [3.21777187e-01 0.00000000e+00 9.83419658e-02 2.31405953e-02
  3.02306640e-01 4.36828095e-03 4.33514170e-02 0.00000000e+00
  2.06713913e-01]
 [2.60725123e-01 0.00000000e+00 2.31232838e-02 6.90936909e-02
  6.11015256e-02 1.17479471e-02 4.81920560e-02 1.78341933e-02
 

#### Fit the Model

In [78]:
# Fit the simple model
# HAVE CELL TO DEFINE HYPERPARAMETERS
# try setting and adding activation function (logistic / softmax / tanh)
# try to make it sum to number
# floor values (np.clip())

regr = MLPRegressor(hidden_layer_sizes=(100,),
                    random_state=1, 
                    activation='logistic',
                    learning_rate_init=0.01, 
                    learning_rate='adaptive',
                    max_iter=500000).fit(X_train, y_train)

#### Make Predictions

In [79]:
# Make predictions for test data

regr.predict(X_test[:1])

array([[ 0.16352232,  0.01110836, -0.00264411,  0.07434502,  0.65651641,
         0.16768583, -0.00207587,  0.01401712, -0.05169422]])

In [80]:
y_test[:1]

array([[2.42847564e-01, 0.00000000e+00, 8.81364203e-04, 7.14916137e-02,
        5.92571897e-01, 8.84974808e-02, 2.88111531e-03, 6.65219150e-04,
        1.63746252e-04]])

In [81]:
# Make this all a function for each row!! This makes is like softmax
floored = np.clip(regr.predict(X_test[:1]), 0,1)
sums = np.sum(floored)
floored/sums

array([[0.15040753, 0.01021745, 0.        , 0.06838241, 0.60386258,
        0.15423711, 0.        , 0.01289292, 0.        ]])

In [82]:
# compute mse instead of r^2 (Actual-predicted etc.)

In [83]:
# could compare mse and r^2 for each column to see what land use it's best at predicting

#### Calc R-squared

In [84]:
# Calculate R-squared

regr.score(X_test, y_test)

-386687.77663841913

In [85]:
regr.predict(X_train[:1])

array([[ 0.26599741,  0.02257287, -0.00319977,  0.08792585,  0.30953277,
         0.06292007,  0.01499567,  0.02365697,  0.34047509]])

In [86]:
regr.score(X_train, y_train)

-4906.541127867366

In [9]:
# 